#!/bin/bash


# Set decoration geometry
berryc border_width       4
berryc inner_border_width 0
berryc title_height       16
berryc top_gap            28

# Set decoration colors
berryc focus_color         E38C8F
berryc unfocus_color       B1E3AD
berryc inner_focus_color   E38C8F
berryc inner_unfocus_color B1E3AD
berryc text_focus_color    B1E3AD
berryc text_unfocus_color  E38C8F

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Tamzen-10"

# wallpaper
feh --bg-max ~/Downloads/strawb.jpg

# polybar
polybar mybar
